### ISSUE TITLE
Some avx macro errors

### ISSUE THREAD

**Issue by mcabbott** [chriselrod/LoopVectorization.jl#144] opened 2020-08-15 18:35 UTC
I have some more `@avx` maybe-bugs for you.

Here it seems to get confused about how much it can re-order things. Some re-ordering would be very welcome, of course, and my program is not smart enough to try:
```julia
function gr!(𝛥mat, 𝛥ℛ, mat, ℛ)
    𝛥ℛ_value = 𝛥ℛ.value
    for j in axes(mat,2)
        for i in axes(mat,1)
            ℰ𝓍1 = conj(𝛥ℛ_value) # could be outside both loops
            ℰ𝓍2 = -(ℛ[j])        # could be outside i loop
            ℰ𝓍3 = exp(ℰ𝓍2)       # could be outside i loop
            ℰ𝓍4 = exp(mat[i, j])
            ℰ𝓍5 = ℰ𝓍3 * ℰ𝓍4
            ℰ𝓍6 = ℰ𝓍1 * ℰ𝓍5
            ℰ𝓍7 = conj(ℰ𝓍6)
            𝛥mat[i, j] = 𝛥mat[i, j] + ℰ𝓍7
        end
    end
    𝛥mat
end
function gr_avx!(𝛥mat, 𝛥ℛ, mat, ℛ)
    𝛥ℛ_value = 𝛥ℛ.value
    @avx for j in axes(mat,2)
        for i in axes(mat,1)
            ℰ𝓍1 = conj(𝛥ℛ_value)
            ℰ𝓍2 = -(ℛ[j])
            ℰ𝓍3 = exp(ℰ𝓍2)
            ℰ𝓍4 = exp(mat[i, j])
            ℰ𝓍5 = ℰ𝓍3 * ℰ𝓍4
            ℰ𝓍6 = ℰ𝓍1 * ℰ𝓍5
            ℰ𝓍7 = conj(ℰ𝓍6)
            𝛥mat[i, j] = 𝛥mat[i, j] + ℰ𝓍7
        end
    end
    𝛥mat
end
gr!(zeros(3,4), (value=1.0,), collect(reshape(1:12, 3,4)), ones(4))
gr_avx!(zeros(3,4), (value=1.0,), collect(reshape(1:12, 3,4)), ones(4)) # ERROR: UndefVarError: ##ℰ𝓍1_ not defined
```

Here it has difficulty with `if` statements, not sure whether this ought to work or not. The last `ifelse` form works, but is wasteful (in my usage) as it calculates `exp` every time:
```julia
function fin!(res, half, m, 𝒶𝓍j=axes(half,1), keep=nothing, final=true)
    for j in 𝒶𝓍j
        𝓇𝒽𝓈 = if isnothing(keep)
                log(half[j]) + m[j]
            else
                res[j] + (log(half[j]) + m[j])
            end
        res[j] = isnothing(final) ? 𝓇𝒽𝓈 : exp(𝓇𝒽𝓈)
    end
    res
end
function fin_avx!(res, half, m, 𝒶𝓍j=axes(half,1), keep=nothing, final=true)
    @avx for j in 𝒶𝓍j
        𝓇𝒽𝓈 = if isnothing(keep)
                log(half[j]) + m[j]
            else
                res[j] + (log(half[j]) + m[j])
            end

        # 𝓇𝒽𝓈2 = isnothing(final) ? 𝓇𝒽𝓈 : exp(𝓇𝒽𝓈) # LoadError: BoundsError: attempt to access 1-element Array{LoopVectorization.Operation,1} at index [0]
        # res[j] = 𝓇𝒽𝓈2


        res[j] = if isnothing(final)
            𝓇𝒽𝓈
        else
            exp(𝓇𝒽𝓈)
        end # LoadError: MethodError: no method matching add_operation!(::LoopVectorization.LoopSet, ::Symbol, ::Symbol, ::Int64, ::Int64)

        # res[j] = ifelse(isnothing(final), 𝓇𝒽𝓈, exp(𝓇𝒽𝓈)) # this way works
    end
    res
end
fin!(ones(4), rand(4), zeros(4))
fin_avx!(ones(4), rand(4), zeros(4))

aa,bb,cc = rand(100), rand(100), rand(100);
@btime fin!($aa, $bb, $cc);
@btime fin_avx!($aa, $bb, $cc);
```

I'm also not sure whether `Ref()` ought to work; perhaps it needs `check_args(::Any) = false` but that doesn't solve all problems:
```julia
function ref1!(out, data, ref)
    @avx for i in axes(out,1)
        out[i] = data[i] + ref[]
    end
    out
end
ref1!(rand(3), ones(3), Ref(4)) # ERROR: StackOverflowError, check_args(::Base.RefValue{Int64})

LoopVectorization.check_args(::Base.RefValue{T}) where {T} = LoopVectorization.check_type(T)

ref1!(rand(3), ones(3), Ref(4)) # ERROR: MethodError: no method matching vload(::Base.RefValue{Int64})

LoopVectorization.check_args(::Base.RefValue{T}) where {T} = false

ref1!(rand(3), ones(3), Ref(4)) # now OK

function ref2!(out, outref, data, ref) # with check_args = false
    @avx for i in 1:3
        acc = 0.0
        for j in 1:3
            acc += data[i,j] * ref[]
        end
        out[i] = out[i] + acc
        outref[] = outref[] + acc
    end
    out, outref
end # ERROR: LoadError: KeyError: key Symbol("##RHS#333") not found

ref2!(rand(3), Ref(Inf), ones(3,3), Ref(4))
```

Finally, two examples where seemingly minor changes affect whether it works:
```julia
function mx!(C::AbstractArray{T}, A, B, keep=nothing) where T
    @avx for j in 1:3
        for i in 1:3

            acc = typemin(T)
            # acc = -999.0 # ok
            # acc = isnothing(keep) ? typemin(T) : C[i, j] # ok

            for k in 1:3
                acc = max(acc, A[i, k] + B[k, j])
            end
            C[i, j] = acc
        end
    end
    C
end
mx!(randn(3,3), randn(3,3), randn(3,3)) # UndefVarError: ####op#7309_0 not defined

function gm!(𝛥A, 𝛥B, 𝛥ℛ, ℛ, A, B)
    @avx for j = 1:3
        for i = 1:3
            for k = 1:3
                flag = ℛ[i, j] == A[i, k] + B[k, j]

                𝛥A[i, k] = ifelse(flag, 𝛥A[i, k] + 𝛥ℛ[i, j], 𝛥A[i, k]) # LoadError: "Reduction not found."
                𝛥B[k, j] = ifelse(flag, 𝛥B[k, j] + 𝛥ℛ[i, j], 𝛥B[k, j])

                # 𝛥A[i, k] += ifelse(flag, 𝛥ℛ[i, j], 0.0) # ok
                # 𝛥B[k, j] += ifelse(flag, 𝛥ℛ[i, j], 0.0)

                # 𝛥A[i, k] += flag * 𝛥ℛ[i, j] # ok
                # 𝛥B[k, j] += flag * 𝛥ℛ[i, j]
            end
        end
    end
    𝛥A, 𝛥B
end
gm!(zeros(3,3), zeros(3,3), ones(3,3), 2ones(3,3), ones(3,3), ones(3,3))
```

Using:
```
(@v1.6) pkg> st LoopVectorization
Status `~/.julia/environments/v1.6/Project.toml`
  [bdcacae8] LoopVectorization v0.8.23
```

**Comment by chriselrod** [comment] 2020-08-15 22:43
Thanks for the 4 bug reports.
While getting all these reports makes the library more robust, have you thought about maybe constructing `LoopSet` objects directly, rather than having it read an `Expr`?
I guess because you have different backends, you get a lot more code-reuse through `Expr` as a common language they all share.

1.
One of the things that probably needs rethinking is the code identifying reductions.
Problems with it were the cause for the first and fourth bug. `# LoadError: "Reduction not found."` makes it obvious that as the problem for the fourth, but the first requires a little more explanation.

Your comment says that it could be outside of both loops, but we don't actually have enough information yet to know that:
```julia
    for j in axes(mat,2)
        for i in axes(mat,1)
            ℰ𝓍1 = conj(𝛥ℛ_value) # could be outside both loops
```
because what if the next few lines were:
```julia
        for k in axes(B,1)
             ℰ𝓍1 += foo(...)
        end
        mat[i,j] = ℰ𝓍1
```
Then obviously we can't actually hoist the entirety of the expression out of the loops.
So what it is supposed to do is
```julia
    temp = conj(𝛥ℛ_value) # the conj itself can be hoisted, just not necessarily the assignment 
    for j in axes(mat,2)
        for i in axes(mat,1)
            ℰ𝓍1 = temp
```
but there were a couple mistakes in connecting the pieces from there.

2. 
> The last ifelse form works, but is wasteful (in my usage) as it calculates exp every time:

I fixed it so that this now gets the correct answer:
```julia
function fin_avx!(res, half, m, 𝒶𝓍j=axes(half,1), keep=nothing, final=true)
    @avx for j in 𝒶𝓍j
        𝓇𝒽𝓈 = if isnothing(keep)
                log(half[j]) + m[j]
            else
                res[j] + (log(half[j]) + m[j])
            end
        res[j] = if isnothing(final)
            𝓇𝒽𝓈
        else
            exp(𝓇𝒽𝓈)
        end
    end
    res
end
```
But note that `if` statements work in LoopVectorization by translating them either into `ifelse` or masked load/store operations (so you can use `if`s to stop yourself from writing to out-of-bounds memory).
Meaning this still calculates both halves.
```julia
julia> aa,bb,cc = rand(100), rand(100), rand(100);

julia> @btime fin!($aa, $bb, $cc);
  1.621 μs (0 allocations: 0 bytes)

julia> @btime fin_avx!($aa, $bb, $cc);
  202.363 ns (0 allocations: 0 bytes)

julia> @btime fin!($aa, $bb, $cc, axes($bb,1), nothing, nothing);
  653.192 ns (0 allocations: 0 bytes)

julia> @btime fin_avx!($aa, $bb, $cc, axes($bb,1), nothing, nothing);
  205.753 ns (0 allocations: 0 bytes)
```
Actually using a branch would not be trivial to implement.
LoopVectorization flattens expressions into a sort of graph.
```julia
julia> res, half, m, 𝒶𝓍j, keep, final = aa, bb, cc, axes(bb,1), nothing, true;

julia> ls = LoopVectorization.@avx_debug for j in 𝒶𝓍j
               𝓇𝒽𝓈 = if isnothing(keep)
                       log(half[j]) + m[j]
                   else
                       res[j] + (log(half[j]) + m[j])
                   end
               res[j] = if isnothing(final)
                   𝓇𝒽𝓈
               else
                   exp(𝓇𝒽𝓈)
               end
           end;
OPS = Tuple{:LoopVectorization,:LOOPCONSTANTINSTRUCTION,LoopVectorization.OperationStruct(0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, LoopVectorization.constant, 0x00, 0x01),Symbol(""),:isnothing,LoopVectorization.OperationStruct(0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000001, LoopVectorization.compute, 0x00, 0x02),:LoopVectorization,:getindex,LoopVectorization.OperationStruct(0x0000000000000001, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, LoopVectorization.memload, 0x01, 0x03),:LoopVectorization,:log,LoopVectorization.OperationStruct(0x0000000000000001, 0x0000000000000000, 0x0000000000000000, 0x0000000000000003, LoopVectorization.compute, 0x00, 0x04),:LoopVectorization,:getindex,LoopVectorization.OperationStruct(0x0000000000000001, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, LoopVectorization.memload, 0x02, 0x05),:LoopVectorization,:+,LoopVectorization.OperationStruct(0x0000000000000001, 0x0000000000000000, 0x0000000000000000, 0x0000000000000405, LoopVectorization.compute, 0x00, 0x06),:LoopVectorization,:getindex,LoopVectorization.OperationStruct(0x0000000000000001, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, LoopVectorization.memload, 0x03, 0x07),:LoopVectorization,:+,LoopVectorization.OperationStruct(0x0000000000000001, 0x0000000000000000, 0x0000000000000000, 0x0000000000000706, LoopVectorization.compute, 0x00, 0x08),:LoopVectorization,:vifelse,LoopVectorization.OperationStruct(0x0000000000000001, 0x0000000000000000, 0x0000000000000000, 0x0000000000020608, LoopVectorization.compute, 0x00, 0x09),:LoopVectorization,:LOOPCONSTANTINSTRUCTION,LoopVectorization.OperationStruct(0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, LoopVectorization.constant, 0x00, 0x0a),Symbol(""),:isnothing,LoopVectorization.OperationStruct(0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x000000000000000a, LoopVectorization.compute, 0x00, 0x0b),:LoopVectorization,:identity,LoopVectorization.OperationStruct(0x0000000000000001, 0x0000000000000000, 0x0000000000000000, 0x0000000000000009, LoopVectorization.compute, 0x00, 0x0c),:LoopVectorization,:exp,LoopVectorization.OperationStruct(0x0000000000000001, 0x0000000000000000, 0x0000000000000000, 0x0000000000000009, LoopVectorization.compute, 0x00, 0x0d),:LoopVectorization,:vifelse,LoopVectorization.OperationStruct(0x0000000000000001, 0x0000000000000000, 0x0000000000000000, 0x00000000000b0c0d, LoopVectorization.compute, 0x00, 0x0e),:LoopVectorization,:setindex!,LoopVectorization.OperationStruct(0x0000000000000001, 0x0000000000000000, 0x0000000000000000, 0x000000000000000e, LoopVectorization.memstore, 0x03, 0x0f)}
ARF = Tuple{LoopVectorization.ArrayRefStruct{:half,Symbol("##vptr##_half")}(0x0000000000000001, 0x0000000000000001, 0x0000000000000000),LoopVectorization.ArrayRefStruct{:m,Symbol("##vptr##_m")}(0x0000000000000001, 0x0000000000000001, 0x0000000000000000),LoopVectorization.ArrayRefStruct{:res,Symbol("##vptr##_res")}(0x0000000000000001, 0x0000000000000001, 0x0000000000000000)}
AM = Tuple{0,Tuple{},Tuple{1,10},Tuple{},Tuple{},Tuple{},Tuple{}}
LPSYM = Tuple{:j}
LB = Tuple{VectorizationBase.StaticLowerUnitRange{1}}
vargs = (VectorizationBase.PackedStridedPointer{Float64,0}(Ptr{Float64} @0x00007fed24d55c50, ()), VectorizationBase.PackedStridedPointer{Float64,0}(Ptr{Float64} @0x00007fed24d55fd0, ()), VectorizationBase.PackedStridedPointer{Float64,0}(Ptr{Float64} @0x00007fed24d558d0, ()), nothing, true, isnothing, isnothing)

julia> ls.operations
 15-element Vector{LoopVectorization.Operation}:
 var"##op#495" = 0
 var"##op#496" = isnothing(var"##op#495")
 var"##op#497" = half[j]
 var"##op#498" = LoopVectorization.log(var"##op#497")
 var"##op#499" = m[j]
 var"##op#500" = var"##op#498" + var"##op#499"
 var"##op#501" = res[j]
 var"##op#502" = var"##op#501" + var"##op#500"
 var"##op#503" = LoopVectorization.vifelse(var"##op#496", var"##op#500", var"##op#502")
 var"##op#504" = 0
 var"##op#505" = isnothing(var"##op#504")
 var"##op#506" = LoopVectorization.identity(var"##op#503")
 var"##op#507" = LoopVectorization.exp(var"##op#503")
 var"##op#508" = LoopVectorization.vifelse(var"##op#505", var"##op#506", var"##op#507")
 res[j] = var"##op#508"
```
So while we could easily replace `vifelse` with `branchifelse(b::Bool, x, y) = b ? x : y`, these expressions still get lowered one at a time. After inlining:
```julia
 var"##op#506" = LoopVectorization.identity(var"##op#503")
 var"##op#507" = LoopVectorization.exp(var"##op#503")
 var"##op#508" = var"##op#505" ? var"##op#506" : var"##op#507"
```
Meaning either LLVM would have to be able to optimize it -- which it can't in the case of `exp` which involves a `ccall` -- or someone would have to add this optimization to LoopVectorization directly.

In the case of `exp`, there's [a PR](https://github.com/chriselrod/SLEEFPirates.jl/pull/11) I'll get around to fixing and merging eventually which will replace the use of `ccall` with a good Julia implementation. That'd let LLVM actually optimize it for us.

3. `LoopVectorization.check_args(::Base.RefValue{T}) where {T} = false`

It should probably be
```julia
LoopVectorization.check_args(::Base.RefValue{T}) where {T} = LoopVectorization.check_type(T)
```
after defining this in VectorizationBase (which I've just done):
```julia
@inline stridedpointer(x::Base.RefValue{T}) where {T} = stridedpointer(Base.unsafe_convert(Ptr{T}, x))
```
Then I get:
```julia
julia> ref1!(rand(3), ones(3), Ref(4))
 3-element Vector{Float64}:
 5.0
 5.0
 5.0
```
with it actually using LoopVectorization, instead of the fallback definition.

`ref2!` will take more work.
Similarly, this doesn't work either
```julia
for j in axes(X,1)
     @avx for i in axes(X,2)
         y[j] += X[i,j]
      end
end
```
The correct thing of course would be to apply `@avx` to the outerloop, but the point of the example is to say `setindex!` where none of the indices depend on any of the loops -- like in your example assigning to the reference -- work at the moment.

The way to get it to work would be to translate it to something like
```julia
for j in axes(X,1)
     _y = y[j]
     @avx for i in axes(X,2)
         _y += X[i,j]
      end
      y[j] = _y
end
```
But someone would actually have to take the time to make the necessary changes. The approach would be to treat the `setindex!`ed variable as an outerreduction, and then generate code to do the store at the end end.

4. 
This reason the minor change caused problems is because it has to try and find what "zero" is with respect to the reduction (i.e., `0.0` if additive, `1.0` if multiplicative, `typemin` for `max`, etc) so that it can initialize the reduction accumulators.
That the correct additive zero is `0` is really obvious if the expression is `A = A + ...`, but much less clear if we instead have `A = foo(A,...)`.
In particular, here we have `vifelse`
so what is the reduction zero? With just `vifelse`, it could be anything:
```julia
a = vifelse(a > b, a, b) => typemin(a)
a = vifelse(a < b, a, b) => typemax(a)
a = vifelse(c, a + b, a + d) => zero(a)
a = vifelse(c, a * b, a * d) => one(a)
```
So it'd have to do some algebra to figure out what it's actually supposed to do.

**Comment by mcabbott** [comment] 2020-08-16 14:52
> have you thought about maybe constructing LoopSet objects directly, rather than having it read an Expr?
> I guess because you have different backends, you get a lot more code-reuse through Expr as a common language

Yes I have, but as you say I'd like to have a plain-Julia version. It is a little strange teaching the robots to talk to each other in English... but it does also make eavesdropping easier! 

1.

> but we don't actually have enough information yet to know that:

Good point. I guess I know it, because the `ℰ𝓍3` are generated by a CSE thing which only assigns once.

2.

> But note that if statements work in LoopVectorization by translating them either into ifelse or masked load/store operations

OK, I did not realise this. My hope was that `final===nothing` would allow the branch with this finaliser function to compile away. But it's pretty easy to generate two versions then, and move the `if isnothing` outside `@avx`, so perhaps I do that.

I hadn't seen https://github.com/chriselrod/SLEEFPirates.jl/pull/11 either. 

3.

OK, thanks for fixing the easy case. I'm not even quite sure how the hard case got onto my list now, will see whether I circle back I guess.

4.

I see, so my examples reducing over `+` and initialising `acc = ifelse(isnothing(keep),zero(T), R[i,j])` have additional intermediate initialisations which are working only because your code figures out the reduction. For now I was mostly trying to get `max` & `min` working nicely.

Anyway thanks for having a look, always informative!

**Closed** 2020-08-16 14:56 UTC
