### ISSUE TITLE
error when loop has a function call

### ISSUE THREAD

**Issue by JackRab** [chriselrod/LoopVectorization.jl#128] opened 2020-06-19 01:01 UTC
Hi,

Thanks for working on this package. On 
```Julia
(@v1.5) pkg> st LoopVectorization
Status `C:\Users\yyi102\.julia\environments\v1.5\Project.toml`
  [bdcacae8] LoopVectorization v0.8.5
```
when 

```Julia
using Parameters
using LoopVectorization

# some settings 
const S = 90               
const β = 0.995   
const J = 3       

#==============================================================#
# a struct of parameters to be estimated
@with_kw struct BusParameters{F<:AbstractFloat}
    θ₁::F = 5.0
    θ₃::Array{F, 1} = [1/J for j in 1:J]
    RC::F = 8.0
end

#=======================================================#
function next_feasible_x(x, d)
    # find all feasible x' given current x and d
    # if d = 1, xₚ = 1, 2, ..., J-1
    # if d = 0, if x <= S-J+1 xₚ = x+j-1, j = 1, 2, ..., J 
    #           if x = S-J+2, xₚ = x+j-1, j = 1, 2, ..., J-1
    #           if x = S-J+3, xₚ = x+j-1, j = 1, 2, ..., J-2, ...
    @assert x<= S
    if d == 1
        return [j for j in 1:J-1]
    end
    if d == 0
        if x <= S-J+1
            return [x+j-1 for j in 1:J]
        else
            return [x+j-1 for j in 1:S-x+1]
        end
    end
end

function T(EV, θ)
    @unpack θ₁, θ₃, RC = θ
    EVₙ = zero(EV)

    @avx for d in 0:1, s in 1:S
        for xₚ in next_feasible_x(s, d)
            EVₙ[d+1, s] += log( exp(xₚ+β*EV[2, xₚ]) + exp(xₚ+β*EV[1, xₚ]) )
        end
    end

    return EVₙ
end

θ₀ = BusParameters()
EV₀ = zeros(2, S)
T(EV₀, θ₀)
```
get the following error
```Julia
julia> T(EV₀, θ₀)
ERROR: UndefVarError: s not defined
Stacktrace:
 [1] T(::Array{Float64,2}, ::BusParameters{Float64}) at .\REPL[12]:5
 [2] top-level scope at REPL[15]:1
```
A more complex example can be found [here](https://gist.github.com/JackRab/4810ace12eb233741bbbccc57994df2f/revisions).

**Comment by chriselrod** [comment] 2020-06-19 02:02
Hi, probably not the answer you were looking for, but this will at least work:
```julia
using Parameters
using LoopVectorization

# some settings 
const S = 90               
const β = 0.995   
const J = 3       

#==============================================================#
# a struct of parameters to be estimated
@with_kw struct BusParameters{F<:AbstractFloat}
    θ₁::F = 5.0
    θ₃::Array{F, 1} = [1/J for j in 1:J]
    RC::F = 8.0
end

#=======================================================#
function next_feasible_x(x, d)
    # find all feasible x' given current x and d
    # if d = 1, xₚ = 1, 2, ..., J-1
    # if d = 0, if x <= S-J+1 xₚ = x+j-1, j = 1, 2, ..., J 
    #           if x = S-J+2, xₚ = x+j-1, j = 1, 2, ..., J-1
    #           if x = S-J+3, xₚ = x+j-1, j = 1, 2, ..., J-2, ...
    @assert x<= S
    if d == 1
        return [j for j in 1:J-1]
    end
    if d == 0
        if x <= S-J+1
            return [x+j-1 for j in 1:J]
        else
            return [x+j-1 for j in 1:S-x+1]
        end
    end
end

function T(EV, θ)
    @unpack θ₁, θ₃, RC = θ
    EVₙ = similar(EV)

    for d in 0:1, s in 1:S
        x = next_feasible_x(s, d)
        EVds = zero(eltype(EV))
        @avx for p in eachindex(x)
            xₚ = x[p]
            EVds += log( exp(xₚ+β*EV[2, xₚ]) + exp(xₚ+β*EV[1, xₚ]) )
        end
        EVₙ[d+1, s] = EVds
    end

    return EVₙ
end

function Tnoavx(EV, θ)
    @unpack θ₁, θ₃, RC = θ
    EVₙ = zero(EV)

    for d in 0:1, s in 1:S # faster without @inbounds  on my computer?
        for xₚ in next_feasible_x(s, d)
            EVₙ[d+1, s] += log( exp(xₚ+β*EV[2, xₚ]) + exp(xₚ+β*EV[1, xₚ]) )
        end
    end

    return EVₙ
end

θ₀ = BusParameters()
EV₀ = zeros(2, S)
T(EV₀, θ₀)
Tnoavx(EV₀, θ₀)
```
Yields:
```julia
julia> Tnoavx(EV₀, θ₀) ≈ T(EV₀, θ₀)
true
````

Anyway, `T` and `Tnoavx` are more or less the same fast. `next_feasible_x` is generally 2 or 3 elements, which isn't much to vectorize.

So, how about:
```julia
function T2(EV, θ)
    @unpack θ₁, θ₃, RC = θ
    EVₜ = fill(log(0.5), 2, S, 3, 2) # log(exp(log(0.5)) + exp(log(0.5)) = 0
    @inbounds for d in 0:1, s in 1:S
        for (p,xₚ) in enumerate(next_feasible_x(s, d))
            EVₜ[d+1, s, p, 1] = muladd(β, EV[1, xₚ], xₚ)
            EVₜ[d+1, s, p, 2] = muladd(β, EV[2, xₚ], xₚ)
        end
    end 
    EVₜl = @view(EVₜ[:, :, :, 1])
    EVₜu = @view(EVₜ[:, :, :, 2])
    @avx for i in eachindex(EVₜl)
        EVₜl[i] = log(exp(EVₜl[i]) + exp(EVₜu[i]))
    end
    return reshape(sum(EVₜl, dims = 3), (2, S))
end
```
The strategy above is to simplify the data structure/iteration space. This means padding the variable axis of the array to be full length, and then making sure it's zeroed out before summing (which we do by initializing the elements as `log(0.5)`).

```julia
julia> Tnoavx(EV₀, θ₀) ≈ T2(EV₀, θ₀)
true
```
This is about three times faster than `Tnoavx` on:
```julia
julia> @benchmark Tnoavx($EV₀, $θ₀)
BenchmarkTools.Trial:
  memory estimate:  19.84 KiB
  allocs estimate:  181
  --------------
  minimum time:     33.105 μs (0.00% GC)
  median time:      33.639 μs (0.00% GC)
  mean time:        35.808 μs (2.76% GC)
  maximum time:     2.650 ms (98.17% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> @benchmark T($EV₀, $θ₀)
BenchmarkTools.Trial:
  memory estimate:  36.72 KiB
  allocs estimate:  541
  --------------
  minimum time:     28.127 μs (0.00% GC)
  median time:      29.346 μs (0.00% GC)
  mean time:        33.127 μs (8.25% GC)
  maximum time:     3.679 ms (98.57% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> @benchmark T2($EV₀, $θ₀)
BenchmarkTools.Trial:
  memory estimate:  31.44 KiB
  allocs estimate:  369
  --------------
  minimum time:     10.258 μs (0.00% GC)
  median time:      11.631 μs (0.00% GC)
  mean time:        14.503 μs (13.73% GC)
  maximum time:     3.072 ms (99.17% GC)
  --------------
  samples:          10000
  evals/sample:     1

(@v1.6) pkg> st LoopVectorization
Status `~/.julia/environments/v1.6/Project.toml`
  [bdcacae8] LoopVectorization v0.8.5 `~/.julia/dev/LoopVectorization`

julia> versioninfo()
Julia Version 1.6.0-DEV.253
Commit 4d94a63bc2* (2020-06-18 08:54 UTC)
Platform Info:
  OS: Linux (x86_64-generic-linux)
  CPU: Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-10.0.0 (ORCJIT, skylake)
```

As for the issue itself, `next_feasible_x(s, d)` is currently problematic. I'd like to get loops whose iteration space is a function of outer loops to work eventually.

P.S.
I didn't want to change the behavior of `next_feasible_x` (i.e., go from returning nothing when d isn't 0 or 1 to throwing an error), but you may want to consider something like this:
```julia
function next_feasible_x(x, d)
    # find all feasible x' given current x and d
    # if d = 1, xₚ = 1, 2, ..., J-1
    # if d = 0, if x <= S-J+1 xₚ = x+j-1, j = 1, 2, ..., J 
    #           if x = S-J+2, xₚ = x+j-1, j = 1, 2, ..., J-1
    #           if x = S-J+3, xₚ = x+j-1, j = 1, 2, ..., J-2, ...
    @assert x<= S
    if d == 1
        return [j for j in 1:J-1]
    elseif d == 0
        if x <= S-J+1
            return [x+j-1 for j in 1:J]
        else
            return [x+j-1 for j in 1:S-x+1]
        end
    else
        throw(DomainError(d, "d must be 0 or 1."))
    end
end
```
This allocates less memory. Julia's supposed to be good at handling unions, but this seemed to help slightly when I tried it.

**Comment by JackRab** [comment] 2020-06-19 03:28
Thanks a lot for your very detailed anatomy of my example. I learned a lot from your explanation. A problem for me is I probably need some time to really understand this part
> The strategy above is to simplify the data structure/iteration space. This means padding the variable axis of the array to be full length, and then making sure it's zeroed out before summing (which we do by initializing the elements as log(0.5)).

And my real working example involves more computation than this simplified example. I guess I can follow your strategy after I understand your code. 
Thanks a lot. I really appreciate your help.

**Comment by mcabbott** [comment] 2020-06-19 08:15
We discussed this a little on slack, and some cut-down versions gave me errors, but worked for others? This happens on two different computers, both macs, LoopVectorization v0.8.5 and v0.7.5:
```
julia> EVₙ = zeros(4,3); EV = rand(2,3);

julia> @avx for d in 0:1
           for s in 1:3
               for xₚ in 1:3
                   EVₙ[d+1,s] = EV[2,xₚ]
               end
           end
       end
ERROR: InexactError: trunc(Int64, Inf)
Stacktrace:
 [1] trunc at ./float.jl:703 [inlined]
 [2] floor at ./float.jl:363 [inlined]
 [3] solve_unroll_constU(::SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true}, ::SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true}, ::Int64) at /Users/me/.julia/packages/LoopVectorization/bI2Fm/src/determinestrategy.jl:360
 [4] solve_unroll(::Symbol, ::Symbol, ::SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true}, ::SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true}, ::Int64, ::Symbol, ::LoopVectorization.Loop, ::LoopVectorization.Loop) at /Users/me/.julia/packages/LoopVectorization/bI2Fm/src/determinestrategy.jl:447
```

**Comment by chriselrod** [comment] 2020-06-19 14:16
> We discussed this a little on slack

Which section? I couldn't find it.

> Thanks a lot for your very detailed anatomy of my example. I learned a lot from your explanation. A problem for me is I probably need some time to really understand this part

I'd be happy to go into more depth, but I figure it'd be good to see the preexisting discussion first.

> This happens on two different computers, both macs, LoopVectorization v0.8.5 and v0.7.5:

I tried on two different computers (AVX2 and AVX512), and could not reproduce those errors on LoopVectorization master or 0.8.5:
```julia
julia> using LoopVectorization
[ Info: Precompiling LoopVectorization [bdcacae8-1622-11e9-2a5c-532679323890]

(@v1.6) pkg> st LoopVectorization
Status `~/.julia/environments/v1.6/Project.toml`
  [bdcacae8] LoopVectorization v0.8.5

julia> EVₙ = zeros(4,3); EV = rand(2,3);

julia> @avx for d in 0:1
           for s in 1:3
               for xₚ in 1:3
                   EVₙ[d+1,s] = EV[2,xₚ]
               end
           end
       end

julia> function h!(M)
           @avx for i in 1:3, j in 1:3
               M[i,j] = (i<=j)
               # M[i,j] = (i==j)
           end
       end
h! (generic function with 1 method)

julia> h!(zeros(3,3))

julia>
```

**Comment by mcabbott** [comment] 2020-06-19 14:40
See if this works, the slack discussion: https://julialang.slack.com/archives/C6A044SQH/p1592511844444100

> could not reproduce those errors

Thanks for having a look. Apparently it's just me :( Actually I get no error now on Julia 1.3, the default binary. My 1.5 has some stuff compiled in, so maybe that's the issue. Although I don't see an obvious signs of piracy:

<details><pre>
julia> h!(zeros(3,3))
ERROR: InexactError: trunc(Int64, Inf)
Stacktrace:
 [1] trunc at ./float.jl:703 [inlined]
 [2] floor at ./float.jl:363 [inlined]
 [3] solve_unroll_constU(::SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true}, ::Int64) at /Users/me/.julia/packages/LoopVectorization/lmGAZ/src/determinestrategy.jl:301
 [4] solve_unroll(::Symbol, ::Symbol, ::SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true}, ::SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true}, ::Int64, ::Symbol, ::LoopVectorization.Loop, ::LoopVectorization.Loop) at /Users/me/.julia/packages/LoopVectorization/lmGAZ/src/determinestrategy.jl:389
 [5] solve_unroll at /Users/me/.julia/packages/LoopVectorization/lmGAZ/src/determinestrategy.jl:361 [inlined]
 [6] evaluate_cost_tile(::LoopVectorization.LoopSet, ::Array{Symbol,1}, ::LoopVectorization.UnrollSymbols) at /Users/me/.julia/packages/LoopVectorization/lmGAZ/src/determinestrategy.jl:713
 [7] choose_tile(::LoopVectorization.LoopSet) at /Users/me/.julia/packages/LoopVectorization/lmGAZ/src/determinestrategy.jl:858
 [8] choose_order_cost at /Users/me/.julia/packages/LoopVectorization/lmGAZ/src/determinestrategy.jl:883 [inlined]
 [9] lower(::LoopVectorization.LoopSet, ::Int64) at /Users/me/.julia/packages/LoopVectorization/lmGAZ/src/lowering.jl:586
 [10] lower_and_split_loops(::LoopVectorization.LoopSet, ::Int64) at /Applications/Julia-1.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 [11] avx_body(::LoopVectorization.LoopSet, ::Tuple{Int8,Int8,Int8}) at /Applications/Julia-1.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 [12] #s126#74 at /Users/me/.julia/packages/LoopVectorization/lmGAZ/src/reconstruct_loopset.jl:473 [inlined]
 [13] #s126#74(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Type{T} where T, ::Type{T} where T, ::Type{T} where T, ::Type{T} where T, ::Any, ::Any, ::Any) at ./none:0
 [14] (::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any,N} where N) at /Applications/Julia-1.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 [15] h!(::Array{Float64,2}) at ./REPL[9]:2
 [16] top-level scope at REPL[10]:1
</pre></details>

**Comment by chriselrod** [comment] 2020-06-19 17:37
[determinestrategy.jl line 301 on LoopVectorization 0.8.5](https://github.com/chriselrod/LoopVectorization.jl/blob/d9541a7a08699d8f8a1ef69244203ca1f15b6b6e/src/determinestrategy.jl#L301)

Versus your error:
>  [3] solve_unroll_constU(::SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true}, ::Int64) at /Users/me/.julia/packages/LoopVectorization/lmGAZ/src/determinestrategy.jl:301

The mismatch suggests it hasn't been updated. Maybe you could try updating and rebuilding your system image?
The error you were getting was fixed in 0.8.5 following your report in this issue: https://github.com/chriselrod/LoopVectorization.jl/issues/126

The function `solve_unroll_constU` now checks whether the denominator is 0 before calling `floor`.

I'll explain my fast example after work, when I have more time.

**Comment by mcabbott** [comment] 2020-06-19 18:41
Ah indeed, it's fixed, the cause must have been my image. Sorry about the confusion.

**Comment by chriselrod** [comment] 2020-06-20 02:03
@JackRab 
> Thanks a lot for your very detailed anatomy of my example. I learned a lot from your explanation. A problem for me is I probably need some time to really understand this part

I think it'd be easier and perhaps more helpful if I answered specific questions you had than if I wrote an overly verbose reply.

But to give a little more background:
Vectorization (in the context of `LoopVectorization`) means using "vector instructions", which is another way of saying SIMD (Single Instruction Multiple Data). Essentially, that means having each CPU instruction work towards calculating multiple loop iterations at a time.
With `Float64`, modern CPUs should be able to calculate 4 or 8 answers per instruction.
Julia's compiler already tries to do this in many cases, but not for functions like `exp` or `log`, but LoopVectorization still does. So code using these functions is an obvious candidate for when LoopVectorization may boost performance.

But if a loop is only 2 or 3 iterations total, some of your potential 4 or 8 operations are wasted.

So the approach is to split the loop into pieces. First, the branchy part with possibly variable numbers of iterations, and then once you've gotten the data neat and tidy, do the computationally intense part (`log` and `exp`) then.

I made another performance improvement below, and added a few comments:
```julia
using Parameters
using LoopVectorization
using BenchmarkTools

# some settings 
const S = 90               
const β = 0.995   
const J = 3       

#==============================================================#
# a struct of parameters to be estimated
@with_kw struct BusParameters{F<:AbstractFloat}
    θ₁::F = 5.0
    θ₃::Array{F, 1} = [1/J for j in 1:J]
    RC::F = 8.0
end

# Returns generator union; rely on constant prop and inlining
@inline function next_feasible_x_gen(x, d)
    # find all feasible x' given current x and d
    # if d = 1, xₚ = 1, 2, ..., J-1
    # if d = 0, if x <= S-J+1 xₚ = x+j-1, j = 1, 2, ..., J 
    #           if x = S-J+2, xₚ = x+j-1, j = 1, 2, ..., J-1
    #           if x = S-J+3, xₚ = x+j-1, j = 1, 2, ..., J-2, ...
    @assert x<= S
    if d == 1
        return (j for j in 1:J-1)
    elseif d == 0
        if x <= S-J+1
            return (x+j-1 for j in 1:J)
        else
            return (x+j-1 for j in 1:S-x+1)
        end
    else
        throw(DomainError(d, "d must be 0 or 1."))
    end
end
function T2(EV, θ)
    @unpack θ₁, θ₃, RC = θ
    EVₜ = fill(log(0.5), 2, S, 3, 2) # log(exp(log(0.5)) + exp(log(0.5)) = 0
    # we're going to calculate log(exp(β * EV[1, xₚ] + xₚ) + exp(β * EV[2, xₚ] + xₚ))
    # because `β * EV[*, xₚ] + xₚ` is hard to vectorize, we calculate them in advance
    Base.Cartesian.@nexprs 2 d -> begin # split the `d` loop 
        @inbounds for s in 1:S
            for (p,xₚ) in enumerate(next_feasible_x_gen(s, d-1))
                EVₜ[d, s, p, 1] = muladd(β, EV[1, xₚ], xₚ)
                EVₜ[d, s, p, 2] = muladd(β, EV[2, xₚ], xₚ)
            end
        end 
    end
    # now we calculate the `log` and `exp`
    EVₜl = @view(EVₜ[:, :, :, 1])
    EVₜu = @view(EVₜ[:, :, :, 2])
    @avx for i in eachindex(EVₜl)
        EVₜl[i] = log(exp(EVₜl[i]) + exp(EVₜu[i]))
    end
    # finally, we sum
    return reshape(sum(EVₜl, dims = 3), (2, S))
end
function T3(EV, θ)
    @unpack θ₁, θ₃, RC = θ
    EVₜ = fill(log(0.5), 2, S, 3, 2) # log(exp(log(0.5)) + exp(log(0.5)) = 0
    Base.Cartesian.@nexprs 2 d -> begin # split the `d` loop 
        @inbounds for s in 1:S
            for (p,xₚ) in enumerate(next_feasible_x_gen(s, d-1))
                EVₜ[d, s, p, 1] = muladd(β, EV[1, xₚ], xₚ)
                EVₜ[d, s, p, 2] = muladd(β, EV[2, xₚ], xₚ)
            end
        end 
    end
    EVₜl = reshape(@view(EVₜ[:, :, :, 1]), (2S, 3))
    EVₜu = reshape(@view(EVₜ[:, :, :, 2]), (2S, 3))
    EVₙ = similar(EV)
    # Like the above, but don't split off the sum
    @avx for i in 1:LoopVectorization.Static(2S)
        EVₙ[i] = log(exp(EVₜl[i,1]) + exp(EVₜu[i,1])) + log(exp(EVₜl[i,2]) + exp(EVₜu[i,2])) + log(exp(EVₜl[i,3]) + exp(EVₜu[i,3]))
    end
    return EVₙ
end

θ₀ = BusParameters();
EV₀ = zeros(2, S);
@benchmark T2($EV₀, $θ₀)
@benchmark T3($EV₀, $θ₀)
```
I'm not sure what happened, but performance is now suddenly better for the old functions, but the new ones with the rehaped data and generator are much faster:
```julia
julia> @benchmark T3($EV₀, $θ₀)
BenchmarkTools.Trial:
  memory estimate:  10.20 KiB
  allocs estimate:  3
  --------------
  minimum time:     2.721 μs (0.00% GC)
  median time:      2.979 μs (0.00% GC)
  mean time:        3.325 μs (6.28% GC)
  maximum time:     153.894 μs (96.43% GC)
  --------------
  samples:          10000
  evals/sample:     9

julia> @benchmark T2($EV₀, $θ₀)
BenchmarkTools.Trial:
  memory estimate:  10.38 KiB
  allocs estimate:  9
  --------------
  minimum time:     3.957 μs (0.00% GC)
  median time:      4.283 μs (0.00% GC)
  mean time:        4.657 μs (4.80% GC)
  maximum time:     192.327 μs (94.57% GC)
  --------------
  samples:          10000
  evals/sample:     7

julia> @benchmark T($EV₀, $θ₀)
BenchmarkTools.Trial:
  memory estimate:  19.84 KiB
  allocs estimate:  181
  --------------
  minimum time:     15.111 μs (0.00% GC)
  median time:      15.500 μs (0.00% GC)
  mean time:        17.682 μs (4.92% GC)
  maximum time:     2.353 ms (98.44% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> @benchmark Tnoavx($EV₀, $θ₀)
BenchmarkTools.Trial:
  memory estimate:  19.84 KiB
  allocs estimate:  181
  --------------
  minimum time:     20.788 μs (0.00% GC)
  median time:      21.221 μs (0.00% GC)
  mean time:        23.253 μs (3.82% GC)
  maximum time:     2.415 ms (98.56% GC)
  --------------
  samples:          10000
  evals/sample:     1
```
I don't want to change your code too much more, in fear of starting to deviate too much from your actual problem, since I haven't looked at it.

I'm sure you could improve performance further, e.g. I haven't addressed this yet:
> Also, you can optimize T2 further. For example, if d == 1, then next_feasible_x(x, d) is guaranteed to be of length 2, meaning you could easily shave off 1/6th of the exp and log calls T2 is doing.

But I think this would be simpler to do efficiently if you'd be willing to accept transposed output, but decisions like that require understanding the broader context.

I hope these give you some helpful ideas. Please feel free to ask any questions you may have.

**Comment by JackRab** [comment] 2020-06-20 13:23
Hi @chriselrod,

Thank you so much for your very clear demonstration. Now I think I got a better understanding of how to make my program more efficient. I have accumulated a lot of useful techniques since I started using Julia especially with the help of more experienced programmers like you, Michael, and Mason, etc.  I appreciate all of your help. Maybe we could close this issue now.

**Closed** 2020-06-20 13:23 UTC
